blog/urls.py
from blog import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path("", views.blog, name='home'),
    path("<int:post_id>/", views.post, name='post'),
    path("exemplo/", views.exemplo, name='exemplo'),
]

home/urls.py
from django.urls import path # type: ignore

from .views import *

app_name = "home"

urlpatterns = [
    path('', home, name="main"),
]

project/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include #type: ignore

urlpatterns = [
    path('', include("home.urls")),
    path('blog/', include("blog.urls")),
    path("admin/", admin.site.urls)
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from . import data
from django.http import Http404

def blog(request):
    print("blog")
    
    context = {
        'text': "Olá, blog",
        'posts': data.posts
    }

    return render(request, "blog/index.html", context)

def post(request, post_id):
    post_id = int(post_id)
    found_post = next((post for post in data.posts if post['id'] == post_id), None)

    if not found_post:
        raise Http404('Post não encontrado.')


    context={
        'title': '- ' + found_post['title'],
        'post': found_post,
        'text': "Detalhes do Post",
    }

    return render(
        request,
        "blog/post.html",
        context
    )

def exemplo(request):
    print('exemplo')

    context= {
        "text": "Hola, exemple",
        "title": "Essa é uma página de exemplo -",
    }

    return render(request, "blog/exemplo.html", context)

home/views.py
from django.shortcuts import render

def context_key():
    return {
        "text": "Aplicando context na home",
        "title":" - Home"
    }

def home(request):
    return render(
        request,
        'home/main.html',
        context_key()
    )

blog/templates/blog/exemplo.html
{% extends 'global/base.html' %}

{% block texto %} {{ text }} {% endblock texto %}

blog/templates/blog/index.html
{% extends "global/base.html" %}

{% block texto %}{{text}}{% endblock texto %}


{# override>posts #}
{% block posts %}
    {% for post in posts %}
        {% include "global/partials/postblock.html" %}
    {% endfor %}
{% endblock posts %}

blog/templates/blog/post.html
{% extends "global/base.html" %}

{% block texto %}{{ text }}{% endblock texto %}

{% block posts %}
    <article class="post single-post">
        <header>
            <h2 class="post__title">
                <a href="{% url 'blog:post' post.id %}">
                    {{ post.title }}
                </a>
            </h2>
        </header>
        <div class="post__body">
            {{ post.body }}
        </div>
    </article>
{% endblock posts %}

home/templates/home/main.html
{% extends "global/base.html" %}

// palavra 'texto' se refere a um tipo id
{% block texto %}
{{ text }}
{% endblock %}